[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Enable Next.js plugin for proper function deployment
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle API routes properly
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Handle Next.js static files
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Handle PWA files
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

# Handle all other routes - SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"

# Environment variables for deploy previews
[context.deploy-preview.environment]
  NODE_ENV = "production"
